# Generated by Django 3.2.2 on 2021-06-01 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_title_post_judul'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='judul',
            new_name='title',
        ),
    ]
