# Generated by Django 3.2.2 on 2021-06-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_judul_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='name@web.com', max_length=254),
        ),
    ]
