# Generated by Django 3.2.2 on 2021-06-04 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_alamat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='waktu',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
