# Generated by Django 3.2.2 on 2022-06-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='author',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='judul',
            new_name='nim',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='body',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='jk',
            field=models.CharField(choices=[('Perempuan', 'Perempuan'), ('Laki-Laki', 'Laki-Laki')], default='Laki-Laki', max_length=20),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='prodi',
            field=models.CharField(default='nama', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='tanggal_lahir',
            field=models.CharField(default='nim', max_length=20),
            preserve_default=False,
        ),
    ]
